version: 2
updates:
  - package-ecosystem: "pnpm" # 사용할 패키지 매니저 (pip, maven, docker 등)
    directory: "/" # 매니페스트 파일 위치
    schedule:
      interval: "daily" # 확인 주기 (daily, weekly, monthly)
    open-pull-requests-limit: 10 # 동시에 열어둘 PR 최대 개수
    labels:
      - "dependencies" # PR에 붙일 라벨
